/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Chofer;

import Controlador.ChoferController;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Almi-
 */
public class ChoferForm extends javax.swing.JFrame {

    /**
     * Creates new form ChoferForm
     */
    public ChoferForm() throws SQLException {
        initComponents();
        ChoferController chofer = new ChoferController();
        chofer.ChoferController(this);
        chofer.setCform(this);
        chofer.Load();
        jLabel10.setVisible(false);
        txtContra.setVisible(false);
        //Icono de la aplicacion
        setIconImage(new ImageIcon (getClass().getResource("/Vista/Login/Camion.png")).getImage());
        //Tamaño de las imagenes
        ImageIcon img=new ImageIcon(getClass().getResource("/Vista/Chofer/chofer.png"));
        ImageIcon img2=new ImageIcon(getClass().getResource("/Images/buscar.png"));
        Icon tmn=new ImageIcon(img.getImage().getScaledInstance(lblChofer.getWidth(), lblChofer.getHeight(), Image.SCALE_DEFAULT));
        Icon tmn2=new ImageIcon(img2.getImage().getScaledInstance(lblBuscar.getWidth(), lblBuscar.getHeight(), Image.SCALE_DEFAULT));
        lblBuscar.setIcon(tmn2);
        lblChofer.setIcon(tmn);
        this.repaint();
//            txtCi.addKeyListener(new java.awt.event.KeyAdapter() {
//        public void keyTyped(java.awt.event.KeyEvent evt) {
//            txtCiKeyTyped(evt);
//        }
//    });
//    txtCelu.addKeyListener(new java.awt.event.KeyAdapter() {
//        public void keyTyped(java.awt.event.KeyEvent evt) {
//            txtCiKeyTyped(evt);
//        }
//    });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCont = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCi = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCelu = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDir = new javax.swing.JTextField();
        cbDisp = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblChofer = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtContra = new javax.swing.JTextField();
        btnRegresarMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setUndecorated(true);

        panelCont.setBackground(new java.awt.Color(223, 223, 236));
        panelCont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickPanel(evt);
            }
        });
        panelCont.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        panelCont.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 804, 188));

        jLabel2.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 180, 85));
        jLabel2.setText("Chofer");
        panelCont.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("CI");
        panelCont.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 107, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Nombre");
        panelCont.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 148, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("Apellido");
        panelCont.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 189, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setText("Celular");
        panelCont.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 237, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setText("Correo");
        panelCont.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setText("Direccion");
        panelCont.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setText("Contraseña");
        jLabel10.setEnabled(false);
        panelCont.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 237, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setText("Disponibilidad");
        panelCont.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 296, -1, -1));

        txtCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiActionPerformed(evt);
            }
        });
        txtCi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCiKeyTyped(evt);
            }
        });
        panelCont.add(txtCi, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 111, 109, -1));
        panelCont.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 152, 109, -1));
        panelCont.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 193, 109, -1));

        txtCelu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCeluActionPerformed(evt);
            }
        });
        txtCelu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCeluKeyTyped(evt);
            }
        });
        panelCont.add(txtCelu, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 241, 109, -1));
        panelCont.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 178, -1));
        panelCont.add(txtDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 178, -1));

        cbDisp.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cbDisp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "No disponible" }));
        panelCont.add(cbDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 296, 93, -1));

        btnGuardar.setBackground(new java.awt.Color(192, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        panelCont.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 158, 121, -1));

        btnEliminar.setBackground(new java.awt.Color(192, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        panelCont.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 230, 121, -1));

        btnEditar.setBackground(new java.awt.Color(192, 255, 255));
        btnEditar.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnEditar.setText("Editar");
        panelCont.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 158, 121, -1));

        btnLimpiar.setBackground(new java.awt.Color(192, 255, 255));
        btnLimpiar.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        panelCont.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 230, 121, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("F. Nacimiento");
        panelCont.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));
        panelCont.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 193, 178, -1));

        lblChofer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Chofer/chofer.png"))); // NOI18N
        panelCont.add(lblChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 30, 113, 100));
        panelCont.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 189, -1));

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscar.png"))); // NOI18N
        panelCont.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 48, 42));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setText("Buscar");
        panelCont.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        txtContra.setEnabled(false);
        panelCont.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 241, 178, -1));

        btnRegresarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegresoMenú.png"))); // NOI18N
        panelCont.add(btnRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCont, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCont, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clickPanel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickPanel
        this.txtCi.setEditable(true);
    }//GEN-LAST:event_clickPanel

    private void txtCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiActionPerformed
        // TODO add your handling code here:
        //validarNumerosYLetras(txtCi);
    }//GEN-LAST:event_txtCiActionPerformed

    private void txtCeluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCeluActionPerformed
        // TODO add your handling code here:
       // validarNumerosYLetras(txtCelu);
    }//GEN-LAST:event_txtCeluActionPerformed

    private void txtCiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiKeyTyped
        // TODO add your handling code here:
            String currentText = txtCi.getText();

    // Verificar si el carácter presionado es un número y la longitud no excede 10
    if (!Character.isDigit(evt.getKeyChar()) || currentText.length()== 10) {
        // Consumir el evento, evitando que el carácter se muestre en el campo de texto
        evt.consume();

        // Mostrar mensaje de error
        JOptionPane.showMessageDialog(null, "DEBEN SER SOLO NUMEROS Y HASTA 10 DIGITOS", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_txtCiKeyTyped

    private void txtCeluKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCeluKeyTyped
        // TODO add your handling code here:
        String currentText = txtCelu.getText();

    // Verificar si el carácter presionado es un número y la longitud no excede 10
    if (!Character.isDigit(evt.getKeyChar()) || currentText.length()== 10) {
        // Consumir el evento, evitando que el carácter se muestre en el campo de texto
        evt.consume();

        // Mostrar mensaje de error
        JOptionPane.showMessageDialog(null, "DEBEN SER SOLO NUMEROS Y HASTA 10 DIGITOS", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_txtCeluKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ChoferForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ChoferForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnRegresarMenu;
    public javax.swing.JComboBox<String> cbDisp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblChofer;
    private javax.swing.JPanel panelCont;
    public javax.swing.JTable table;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtCelu;
    public javax.swing.JTextField txtCi;
    public javax.swing.JTextField txtContra;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtDir;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    
}
